### PR TITLE
Add CompassAlwaysOn (for HK 1.5)

### PR DESCRIPTION
**Pull request by flibber-hk**

### CODE REVIEW

**Comment by SFGrenade** [comment]
Your version, can you change that to a 4-digit version number? (like 0.9.0.0)

**Comment by Ruttie2006** [comment]
What are those version numbers for?

**Comment by SFGrenade** [comment]
to check if a mod needs to be updated

**Comment by flibber-hk** [comment]
Oh, hopefully it works now

**Pull request merged**
