### PR TITLE
Create dependabot.yml

### PR DESCRIPTION
**Pull request by flibber-hk**

### CODE REVIEW

**Comment by flibber-hk** [comment]
https://github.com/hk-modding/modlinks/actions/runs/3455206562

Apparently node.js 12 actions are deprecated, and apparently dependabot is the easiest way to fix it. I just yoinked a config file from @BadMagic100 , I assume that is good enough for modlinks' purposes

**Comment by fifty-six** [comment]
Seems easier to just change actions/checkout@v2 to actions/checkout@v3 ngl

**Comment by SFGrenade** [comment]
could even do `actions/checkout@v3.1.0` just to be that bit more up to date

**Comment by flibber-hk** [comment]
True - could add the dependabot anyway though?

**Comment by flibber-hk** [comment]
OK so I changed v2 to v3 in this PR - up to you if you prefer to have the dependabot or not

**Comment by fifty-six** [comment]
dependabot sends like 3 quadrillion PRs imo but idk what you guys think of it

**Comment by flibber-hk** [comment]
> dependabot sends like 3 quadrillion PRs imo but idk what you guys think of it

That seems slightly cringe if true - I haven't used dependabot before, I would have assumed it only sends PRs when actions/checkout is updated to a new major version though (at least, when I added the dependabot.yml file [manually](https://github.com/flibber-hk/HollowKnight.RandomizableLevers/compare/70131bda6883e1e6400dcc4a422ace420a54fc3c...b0d6beccd9b6800ece25e4d54e14451d76b5efad) it only tried to change dependencies to the next major version in my build.yml file)

**Comment by fifty-six** [comment]
I mean in general but yeah that's fair tbh

**Comment by BadMagic100** [comment]
Fwiw, using v3 over v3.1.0 is highly preferred (it aliases the latest 3.Y.Z and you can verify this with repo tags). As a result, dependabot should open substantially fewer PRs for actions than other ecosystems because it will only include major version updates (and, if number of PRs became a concern despite this, there are a number of filtering rules which could be applied)

**Pull request merged**
