### PR TITLE
Add GodSoul To Modlinks

### PR DESCRIPTION
**Pull request by Nexade**
If you have any questions or need to message me: Nexade#4250. (This is my first time so I have no idea what I do or don't need to do)

### CODE REVIEW

**Comment by fifty-six** [comment]
What is this supposed to do? Increase the enemy count and remove healing? I had random beams in one room and a geo chest in another but not much else. Also, I'd recommend using the actual preloading system instead of loading them after someone loads a save.

**Comment by Nexade** [comment]
> ~What is this supposed to do? Increase the enemy count and remove healing? I had random beams in one room and a geo chest in another but not much else.~ Nevermind, I found some of the area effects. A list or something in the README would be really nice though. Also, I'd recommend using the actual preloading system instead of loading them after someone loads a save.

Sorry about all the weird inconveniences, it's my first time. Do I need to change anything before the mod is added to the API?

**Comment by fifty-six** [comment]
Your SHA256 is off, but the rest seems fine. You don't need to change anything but using your own preloading system is going to be more error prone and there's still a lot of exceptions being thrown when I use the mod. I can merge it anyways though.

**Comment by Nexade** [comment]
Thanks! I probably won't change anything, I'll just take on the feedback for my next project. :)

**Comment by fifty-six** [comment]
You do need to change the SHA256 in this PR though, it's invalid.

**Comment by Nexade** [comment]
... and how do I do that? I went to the GodSoul github page and went to 'commit' the zip file. Then I copied the last part of the url which looked like the other SHA256 things. As you've probably found out by now I have no idea what I'm doing

**Comment by fifty-six** [comment]
Put the zip through [something like this](https://emn178.github.io/online-tools/sha256_checksum.html) or right click -> CRC-1 -> SHA256 if you have 7-Zip.

**Comment by Nexade** [comment]
I think I did it. I've just edited my edit, but if it doesn't work here it is: AC7D27A1F9E286C4F533BDDCFAFACC4971608FDBF2B06DB6E5586839C9E82DB7

**Comment by Nexade** [comment]
Also, just asking, if I update my mod in the future, will I need to change anything here, or will it not matter?

**Comment by fifty-six** [comment]
If you update your mod in the future, you need to PR a change to the SHA1, download link (to the newest release), and the version (so it gets updated for the users).

**Comment by Nexade** [comment]
Thanks :)

**Pull request merged**
