### PR TITLE
Add GlassSoul

### PR DESCRIPTION
**Pull request by TheMulhima**

### CODE REVIEW

**Comment by SFGrenade** [comment]
can't merge if i can't verify sha256's are correct

**Comment by fifty-six** [comment]
public now

**Comment by fifty-six** [comment]
I reverted this, it isn't ported correctly. The damage increase was only to nail, unless this is an intentional difference?

**Comment by TheMulhima** [comment]
other than nail what other attack do I need to increase damage of?

**Comment by fifty-six** [comment]
You're increasing all of them instead of *just* the nail. Spells, glowing womb, fluke, etc also use HitInstance.

**Pull request merged**
