### PR TITLE
Add optional Authors node

### LINKED ISSUE #764: Optional author(s) field
Hello! It would be great to be able to see who to credit for all the mods listed here, what would it take to add an optional "Authors" field that can be pulled from this list? I wouldn't expect mods to be backfilled quickly, but new/updated mods could have the authors added, and it would be great to be able to pull that into various other mod listing tools that source from this list.

Assuming this change just requires adding the field to `Schemas/ModLinks.xml`, I'd be happy to create a PR for this too! It looks like it would basically just require adding:
```xml
<xs:sequence minOccurs="0" maxOccurs="1">
  <xs:element name="Authors" type="mm:AuthorListType" />
</xs:sequence>
```

### PR DESCRIPTION
**Pull request by Spozder**
Closes #764

### CODE REVIEW

**Comment by SFGrenade** [comment]
uh, i suppose `xmllint` wants the block of
```xml
<xs:complextType name="AuthorListType">
  <xs:sequence minOccurs="1" maxOccurs="unbounded">
    <xs:element name="Author" type="mm:NameStringType" />
  </xs:sequence>
</xs:complextType>
```
to be above `<xs:simpleType name="NameStringType">`

**Comment by SFGrenade** [comment]
fuck xmllint tbh

**Comment by SFGrenade** [comment]
wait, `complexType` is just misspelled as `complextType`

**Comment by Spozder** [comment]
oh nice ty for fixing that!

**Comment by SFGrenade** [comment]
no problem!

**Pull request merged**
