### PR TITLE
Add DecorationMaster

### PR DESCRIPTION
**Pull request by ygsbzr**

### CODE REVIEW

**Comment by SFGrenade** [comment]
i need to know that you have an OK from both Mickely (DeathCounter) and sawyer (DecorationMaster). Can't just blindly add ports of mods without the original authors approval.

**Comment by ygsbzr** [comment]
emmm,sawyer approve me to do that,but I havent get Mickely approval,sorry for that.

**Comment by Clazex** [comment]
DeathCounter was actually added in #78

**Comment by ygsbzr** [comment]
emmm,sawyer approve me to do that,but I havent get Mickely approval,sorry for that.

**Pull request merged**
