### PR TITLE
Updated Charm-Crab Mod

### PR DESCRIPTION
**Pull request by DistractionCrab**
BTW, w/e discord link you sent last time does not work. You should probably look into adding information about this repository into a README for this repository. It'll help people find the information about this repository. Would definitely help with communicating your workflow.

### CODE REVIEW

**Comment by SFGrenade** [comment]
it was from the hk modding discord and about how to avoid clutter commits (e.g. every one up until the last one/few).
and i think i explicitly said that cross-merging isn't necessary.

**Comment by DistractionCrab** [comment]
Welp, I hope this PR meets the standards you're looking for because I am not part of the discord and there's no other information on what's expected for these. So I'm essentially just winging it from looking at other PR's.

**Comment by SFGrenade** [comment]
the main point was that one could use the online edit from github (which should be https://github.com/hk-modding/modlinks/edit/main/ModLinks.xml) to not have to mainain their own fork. This also bypasses the need to merge the base branch into your fork or rebase your fork. the rest should be as simple as following on-screen directions.

**Comment by SFGrenade** [comment]
oh, before i forget: did you mean to change the version from 1.1.0.0 to 1.0.2.0? just asking because it is a "smaller" version

**Comment by DistractionCrab** [comment]
Yes, the 1.1.0.0 was a typo from last time; I forgot to edit the version number there.

Also I hope the irony of "as simple as following on-screen directions." isn't lost on you, as the idea for how this process was meant to be done is hidden in some discord and there is literally zero information about this discord (links or even its existence) from Nexus, to its linked repo, to the link to the API repo, to here.  So I'm not just being snarky when I'm saying, you should probably add a README in this repo because this has been one of the most frustrating things to figure out what you intend just due to the lack of basic information.  

Sure it's not that hard, but when I set it up correctly the first time last time and am basically told "don't do this" for some mysterious reason, things are going to be pointlessly complex. Especially when it's far from a standard workflows. Sure could I just edit the single file by itself, but that doesn't mean that I'm missing something elsewhere due to the lack of information, so I'm going to do the sensible thing and keeping things organized on my end to minimize errors (see last PR had no conflicts, and this one does because I followed a direction). So I assume you'd be fixing these conflicts instead, which again seems *odd*.

Either way, unless there's something else I need to do I'd like to finish this I've wasted enough time at this point.

**Comment by SFGrenade** [comment]
> Yes, the 1.1.0.0 was a typo from last time; I forgot to edit the version number there.

ah, just asked because mod installers would only give an update notice for higher available versions, but no problem there imo.

> from Nexus

oh, that makes more sense, true, but no one, aside from like a dev or two, puts mods or installers on nexus in the hk modding community.
But i can add a readme with that information.

> I'd like to finish this

yea, i can resolve the merge conflicts and merge this.

**Comment by DistractionCrab** [comment]
Thank you, I appreciate it. I just want to clarify for next time so I'm not being a pain; The general workflow expected is to just edit the file through Github using the standard editor. This will edit in my fork, and this should avoid the conflicts in the future. This way the automatic checks can just proceed as normal right and nothing needs to be manually done?

**Comment by SFGrenade** [comment]
yes, in theory it should be as easy as from the start:
1. not have a fork
2. go to <https://github.com/hk-modding/modlinks/blob/main/ModLinks.xml>
3. click the pencil at the top right corner
4. make the changes
5. scroll to the bottom of the github pages
6. it should give you an option to make a fork/branch with those changes
7. do that and it should also give an option to delete that branch after the PR got merged.

**Pull request merged**
