### PR TITLE
Added Omega Radiance

### PR DESCRIPTION
**Pull request by Talezshadid**
I've added Omega Radiance

### CODE REVIEW

**Comment by SFGrenade** [comment]
as stated in https://github.com/hk-modding/modlinks/pull/1448, waiting for modcommon

**Comment by Talezshadid** [comment]
> as stated in #1448, waiting for modcommon

can i add modcommon or do i have to ask the guys that made it?

**Comment by Talezshadid** [comment]
so there should be no problem in adding this now? im asking because i see modcommon on scarab but not this

**Comment by Talezshadid** [comment]
@SFGrenade are there any issues now?

**Comment by Talezshadid** [comment]
@SFGrenade broooo please i wanna sleep :P

**Pull request merged**
