### PR TITLE
Add Glass Cannon Mod to the modlinks

### PR DESCRIPTION
**Pull request by Nexade**
It's a mod I made for a request on reddit. It makes everything oneshot, including the player.

### CODE REVIEW

**Review by SFGrenade — CHANGES_REQUESTED** [review]
um, are you sure this commit is needed? it looks like it adds mods that already where in modlinks.
IMO reset hard to commit 0c7b06cab6d339f3f0668ba364520ee578ce9e55 and just change the name.

**Comment by Nexade** [comment]
Sorry I never use github. What do you need me to do?

**Comment by SFGrenade** [comment]
first
```
git reset --hard 0c7b06cab6d339f3f0668ba364520ee578ce9e55
```
then change the mod name and nothing else.
then
```
git commit
```

**Comment by Nexade** [comment]
And where do I write these. I did a quick google search and looks like their meant to into git bash, so I tried to download it but nothing happened. Anyways I'm hoping there's another way to hard reset.
(Yeah as I said I never use github)

**Comment by Nexade** [comment]
git reset --hard 0c7b06cab6d339f3f0668ba364520ee578ce9e55

**Comment by SFGrenade** [comment]
resolved in an easier way

**Comment by Nexade** [comment]
Sweet, thanks

**Comment by Nexade** [comment]
I've checked the Scarab launcher but I can't find the mod up there. I don't remember it taking time to update with my last mod but it is now. Is there something wrong?

**Comment by SFGrenade** [comment]
for me it's there:
grafik

**Comment by Nexade** [comment]
Thanks, idk what it was, but I can see it now

**Pull request closed without merging**
