### PR TITLE
Update ModLinks.xml

### PR DESCRIPTION
**Pull request by nerthul11**
Added HallOfGodsRandomizer mod.

### CODE REVIEW

**Comment by flibber-hk** [comment]
Wait, I'm wrong. The issue is that you linked to the release page, not the actual download file

**Comment by Ruttie2006** [comment]
(Correct link would be <https://github.com/nerthul11/HallOfGodsRandomizer/releases/download/1.0.0.0/HallOfGodsRandomizer.zip>, replacing `/releases/tag/` with `/releases/download/`)

**Comment by Ruttie2006** [comment]
This commit does not actually fix the issue, you need to link a download link to the zip file, not to the releases page.

**Comment by nerthul11** [comment]
Okay, made a new commit that should now fix the issue. The previous one was made before reading the comment

**Pull request merged**
